lib/dent_web/router.ex
defmodule DentWeb.Router do
  use DentWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/"  do
    pipe_through :browser
    pow_routes()
  end


  scope "/", DentWeb do
    pipe_through [:browser, :protected]
    get "/", PageController, :index
#    resources "/patients", PatientController
#     resources "/payments", PaymentController

    resources "/patients", PatientController do
      resources "/contracts", ContractController
      resources "/payments", PaymentController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", DentWeb do
  #   pipe_through :api
  # end
end

lib/dent/patients.ex
defmodule Dent.Patients do
  @moduledoc """
  The Patients context.
  """

  import Ecto.Query, warn: false
  alias Dent.Repo
import Torch.Helpers, only: [sort: 1, paginate: 4]
import Filtrex.Type.Config

alias Dent.Patients.Patient

@pagination [page_size: 15]
@pagination_distance 5

@doc """
Paginate the list of patients using filtrex
filters.

## Examples

    iex> list_patients(%{})
    %{patients: [%Patient{}], ...}
"""
@spec paginate_patients(map) :: {:ok, map} | {:error, any}
def paginate_patients(params \\ %{} , doctor_id) do
  params =
    params
    |> Map.put_new("sort_direction", "desc")
    |> Map.put_new("sort_field", "inserted_at")

  {:ok, sort_direction} = Map.fetch(params, "sort_direction")
  {:ok, sort_field} = Map.fetch(params, "sort_field")

  with {:ok, filter} <- Filtrex.parse_params(filter_config(:patients), params["patient"] || %{}),
       %Scrivener.Page{} = page <- do_paginate_patients(filter, params ,doctor_id) do
    {:ok,
      %{
        patients: page.entries,
        page_number: page.page_number,
        page_size: page.page_size,
        total_pages: page.total_pages,
        total_entries: page.total_entries,
        distance: @pagination_distance,
        sort_field: sort_field,
        sort_direction: sort_direction
      }
    }
  else
    {:error, error} -> {:error, error}
    error -> {:error, error}
  end
end

defp do_paginate_patients(filter, params,doctor_id) do

     query = from u in Patient,
          where: u.doctor_id == ^doctor_id


  #Patient
  query
  |> Filtrex.query(filter)
  |> order_by(^sort(params))
  |> paginate(Repo, params, @pagination)
end

@doc """
Returns the list of patients.

## Examples

    iex> list_patients()
    [%Patient{}, ...]

"""
def list_patients do
  Repo.all(Patient)
end

@doc """
Gets a single patient.

Raises `Ecto.NoResultsError` if the Patient does not exist.

## Examples

    iex> get_patient!(123)
    %Patient{}

    iex> get_patient!(456)
    ** (Ecto.NoResultsError)

"""
def get_patient!(id), do: Repo.get!(Patient, id)

@doc """
Creates a patient.

## Examples

    iex> create_patient(%{field: value})
    {:ok, %Patient{}}

    iex> create_patient(%{field: bad_value})
    {:error, %Ecto.Changeset{}}

"""
def create_patient(attrs \\ %{}) do
  %Patient{}
  |> Patient.changeset(attrs)
  |> Repo.insert()
end

@doc """
Updates a patient.

## Examples

    iex> update_patient(patient, %{field: new_value})
    {:ok, %Patient{}}

    iex> update_patient(patient, %{field: bad_value})
    {:error, %Ecto.Changeset{}}

"""
def update_patient(%Patient{} = patient, attrs) do
  patient
  |> Patient.changeset(attrs)
  |> Repo.update()
end

@doc """
Deletes a Patient.

## Examples

    iex> delete_patient(patient)
    {:ok, %Patient{}}

    iex> delete_patient(patient)
    {:error, %Ecto.Changeset{}}

"""
def delete_patient(%Patient{} = patient) do
  Repo.delete(patient)
end

@doc """
Returns an `%Ecto.Changeset{}` for tracking patient changes.

## Examples

    iex> change_patient(patient)
    %Ecto.Changeset{source: %Patient{}}

"""
def change_patient(%Patient{} = patient) do
  Patient.changeset(patient, %{})
end

defp filter_config(:patients) do
  defconfig do
    text :identity_number
      text :name
      text :surname
      text :phone
      text :email
      date :birth_date
      
  end
end
end

lib/dent/patients/patient.ex
defmodule Dent.Patients.Patient do
  use Ecto.Schema
  import Ecto.Changeset

  schema "patients" do
    field :birth_date, :naive_datetime
    field :email, :string
    field :identity_number, :string
    field :name, :string
    field :phone, :string
    field :surname, :string
    field :doctor_id, :id

    timestamps()
  end

  @doc false
  def changeset(patient, attrs) do
    patient
    |> cast(attrs, [:identity_number, :name, :surname, :phone, :email, :birth_date, :doctor_id])
    |> validate_required([:identity_number, :name, :surname, :phone, :email, :birth_date])
  end
end

lib/dent_web/controllers/patient_controller.ex
defmodule DentWeb.PatientController do
  use DentWeb, :controller

  alias Dent.Patients
  alias Dent.Patients.Patient
  alias Dent.Helpers.Utils

  plug(:put_layout, {DentWeb.LayoutView, "torch.html"})

  def index(conn, params) do
    case Patients.paginate_patients(params,Utils.get_doctor_id(conn)) do
      {:ok, assigns} ->
        render(conn, "index.html", assigns)
      error ->
        conn
        |> put_flash(:error, "There was an error rendering Patients. #{inspect(error)}")
        |> redirect(to: Routes.patient_path(conn, :index))
    end
  end

  def new(conn, _params) do
    changeset = Patients.change_patient(%Patient{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"patient" => patient_params}) do
    case Patients.create_patient(Utils.add_doctor_id(patient_params,conn)) do
      {:ok, patient} ->
        conn
        |> put_flash(:info, "Patient created successfully.")
        |> redirect(to: Routes.patient_path(conn, :show, patient))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    patient= Utils.get_model(Patient,id,conn)
    #patient = Patients.get_patient!(id)
    total_payments=Dent.Payments.get_sum_of_payments(Utils.get_doctor_id(conn),patient.id)
    total_contracts=Dent.Contracts.get_sum_of_contracts(Utils.get_doctor_id(conn),patient.id)
    kalan_borc= total_contracts-total_payments
    render(conn, "show.html", patient: patient , total_payments: total_payments , total_contracts: total_contracts , kalan_borc: kalan_borc )
  end

  def edit(conn, %{"id" => id}) do
    #patient = Patients.get_patient!(id)
    patient= Utils.get_model(Patient,id,conn)
    changeset = Patients.change_patient(patient)
    render(conn, "edit.html", patient: patient, changeset: changeset)
  end

  def update(conn, %{"id" => id, "patient" => patient_params}) do
    #patient = Patients.get_patient!(id)
    patient= Utils.get_model(Patient,id,conn)

    case Patients.update_patient(patient, patient_params) do
      {:ok, patient} ->
        conn
        |> put_flash(:info, "Patient updated successfully.")
        |> redirect(to: Routes.patient_path(conn, :show, patient))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", patient: patient, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    patient= Utils.get_model(Patient,id,conn)
    #patient = Patients.get_patient!(id)
    {:ok, _patient} = Patients.delete_patient(patient)

    conn
    |> put_flash(:info, "Patient deleted successfully.")
    |> redirect(to: Routes.patient_path(conn, :index))
  end
end

lib/dent_web/views/patient_view.ex
defmodule DentWeb.PatientView do
  use DentWeb, :view

  import Torch.TableView
  import Torch.FilterView
end

lib/dent_web/templates/patient/edit.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "Cancel", to: Routes.patient_payment_path(@conn, :index), class: "torch-button" %>
  </div>
</section>

<section id="torch-header-and-content">
  <div class="torch-container">
    <div class="header">
      <h3>Edit Patient</h3>
    </div>
    <%= render "form.html", Map.put(assigns, :action, Routes.patient_payment_path(@conn, :update, @patient)) %>
  </div>
</section>

lib/dent_web/templates/patient/form.html.eex
<%= form_for @changeset, @action, [multipart: true, id: "torch-form"], fn f -> %>
  <fieldset class="torch-panel">
    <legend>
      <span>Details</span>
    </legend>
    <%= if @changeset.action do %>
      <p class="torch-form-error">Oops, something went wrong! Please check the errors below.</p>
    <% end %>
  
    <div class="torch-form-group">
      <%= label f, :identity_number %>
      <%= text_input f, :identity_number %>
      <%= error_tag f, :identity_number %>
    </div>
  
    <div class="torch-form-group">
      <%= label f, :name %>
      <%= text_input f, :name %>
      <%= error_tag f, :name %>
    </div>
  
    <div class="torch-form-group">
      <%= label f, :surname %>
      <%= text_input f, :surname %>
      <%= error_tag f, :surname %>
    </div>
  
    <div class="torch-form-group">
      <%= label f, :phone %>
      <%= text_input f, :phone %>
      <%= error_tag f, :phone %>
    </div>
  
    <div class="torch-form-group">
      <%= label f, :email %>
      <%= text_input f, :email %>
      <%= error_tag f, :email %>
    </div>
  
    <div class="torch-form-group">
      <%= label f, :birth_date %>
      <%= datetime_select f, :birth_date  , year: [options: 1900..2100] %>
      <%= error_tag f, :birth_date %>
    </div>
  
    <div class="torch-submit-form">
      <%= submit "Submit", class: "torch-submit-button" %>
    </div>
  </fieldset>
<% end %>

lib/dent_web/templates/patient/index.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "New Patient", to: Routes.patient_path(@conn, :new) %>
  </div>
</section>
<section id="torch-index-content">
  <div class="torch-container">
    <section id="torch-filters">
      <h3>Find Patients</h3>
      <%= form_tag @conn.request_path, method: :get, id: "torch-filters-form" do %>
        
          <div class="field">
            <label>Identity number</label>
            <%= filter_select(:patient, :identity_number, @conn.params) %>
            <%= filter_string_input(:patient, :identity_number, @conn.params) %>
          </div>
        
          <div class="field">
            <label>Name</label>
            <%= filter_select(:patient, :name, @conn.params) %>
            <%= filter_string_input(:patient, :name, @conn.params) %>
          </div>
        
          <div class="field">
            <label>Surname</label>
            <%= filter_select(:patient, :surname, @conn.params) %>
            <%= filter_string_input(:patient, :surname, @conn.params) %>
          </div>
        
          <div class="field">
            <label>Phone</label>
            <%= filter_select(:patient, :phone, @conn.params) %>
            <%= filter_string_input(:patient, :phone, @conn.params) %>
          </div>
        
          <div class="field">
            <label>Email</label>
            <%= filter_select(:patient, :email, @conn.params) %>
            <%= filter_string_input(:patient, :email, @conn.params) %>
          </div>
        
        
        
          <div class="field">
            <label>Birth date</label>
            <%= filter_date_input(:patient, :birth_date, @conn.params) %>
          </div>
        
        
        <button type="submit" class="torch-button">Search</button>
        <%= link "Clear Filters", to: Routes.patient_path(@conn, :index) %>
      <% end %>

    </section>

    <section id="torch-table">
    <%= if length(@patients) > 0 do %>
      <table>
        <thead>
          <tr>
            
              <th><%= table_link(@conn, "Identity number", :identity_number) %></th>
            
              <th><%= table_link(@conn, "Name", :name) %></th>
            
              <th><%= table_link(@conn, "Surname", :surname) %></th>
            
              <th><%= table_link(@conn, "Phone", :phone) %></th>
            
              <th><%= table_link(@conn, "Email", :email) %></th>
            
              <th><%= table_link(@conn, "Birth date", :birth_date) %></th>
            
            <th><span>Actions</span></th>
          </tr>
        </thead>
        <tbody>
          <%= for patient <- @patients do %>
            <tr>
              
                <td><%= patient.identity_number %></td>
              
                <td><%= patient.name %></td>
              
                <td><%= patient.surname %></td>
              
                <td><%= patient.phone %></td>
              
                <td><%= patient.email %></td>
              
                <td><%= patient.birth_date %></td>
              
              <td class="torch-actions">
                <span><%= link "Show", to: Routes.patient_path(@conn, :show, patient) %></span>
                <span><%= link "Ödeme", to: Routes.patient_payment_path(@conn, :new , patient.id) %>   </span>
                <span><%= link "Edit", to: Routes.patient_path(@conn, :edit, patient) %></span>
                <span><%= link "Delete", to: Routes.patient_path(@conn, :delete, patient), method: :delete, data: [confirm: "Are you sure?"] %></span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= render Torch.PaginationView, "_pagination.html", assigns %>
    <% else %>
      <p class="torch-no-data">No Patients match your search.</p>
    <% end %>
    </section>
  </div>
</section>

lib/dent_web/templates/patient/new.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "Cancel", to: Routes.patient_path(@conn, :index), class: "torch-button" %>
  </div>
</section>

<section id="torch-header-and-content">
  <div class="torch-container">
    <div class="header">
      <h3>New Patient</h3>
    </div>
    <%= render "form.html", Map.put(assigns, :action, Routes.patient_path(@conn, :create)) %>
  </div>
</section>

lib/dent_web/templates/patient/show.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "Edit", to: Routes.patient_path(@conn, :edit, @patient), class: "torch-button" %>
    <%= link "Back", to: Routes.patient_path(@conn, :index), class: "torch-button" %>

     <%= link "Hastanın Kontratları", to: Routes.patient_contract_path(@conn, :index , @patient), class: "torch-button" %>
     <%= link "Ödeme", to: Routes.patient_payment_path(@conn, :new , @patient.id) %>

  </div>
</section>

<section id="torch-header-and-content">
  <div class="torch-container">
    <div class="header">
      <h3>Patient Details</h3>
    </div>
    <ul>

        <li>
          <div class="torch-show-label">Kalan Borç:</div>
          <div class="torch-show-data"><%= @kalan_borc %></div>
        </li>

         <li>
          <div class="torch-show-label">Toplam Ödenen:</div>
          <div class="torch-show-data"><%= @total_payments %></div>
        </li>

         <li>
          <div class="torch-show-label">Bütün Mukaveleler Toplamı:</div>
          <div class="torch-show-data"><%= @total_contracts %></div>
        </li>

      
        <li>
          <div class="torch-show-label">Identity number:</div>
          <div class="torch-show-data"><%= @patient.identity_number %></div>
        </li>
      
        <li>
          <div class="torch-show-label">Name:</div>
          <div class="torch-show-data"><%= @patient.name %></div>
        </li>
      
        <li>
          <div class="torch-show-label">Surname:</div>
          <div class="torch-show-data"><%= @patient.surname %></div>
        </li>
      
        <li>
          <div class="torch-show-label">Phone:</div>
          <div class="torch-show-data"><%= @patient.phone %></div>
        </li>
      
        <li>
          <div class="torch-show-label">Email:</div>
          <div class="torch-show-data"><%= @patient.email %></div>
        </li>
      
        <li>
          <div class="torch-show-label">Birth date:</div>
          <div class="torch-show-data"><%= @patient.birth_date %></div>
        </li>
      
    </ul>
  </div>
</section>