lib/dent_web/router.ex
defmodule DentWeb.Router do
  use DentWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/"  do
    pipe_through :browser
    pow_routes()
  end


  scope "/", DentWeb do
    pipe_through [:browser, :protected]
    get "/", PageController, :index
#    resources "/patients", PatientController
#     resources "/payments", PaymentController

    resources "/patients", PatientController do
      resources "/contracts", ContractController
      resources "/payments", PaymentController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", DentWeb do
  #   pipe_through :api
  # end
end

lib/dent/payments.ex
defmodule Dent.Payments do
  @moduledoc """
  The Payments context.
  """

  import Ecto.Query, warn: false
  alias Dent.Repo
import Torch.Helpers, only: [sort: 1, paginate: 4]
import Filtrex.Type.Config

alias Dent.Payments.Payment

@pagination [page_size: 15]
@pagination_distance 5

@doc """
Paginate the list of payments using filtrex
filters.

## Examples

    iex> list_payments(%{})
    %{payments: [%Payment{}], ...}
"""
#@spec paginate_payments(map) :: {:ok, map} | {:error, any}
def paginate_payments(params \\ %{},doctor_id,patient_id) do
  params =
    params
    |> Map.put_new("sort_direction", "desc")
    |> Map.put_new("sort_field", "inserted_at")

  {:ok, sort_direction} = Map.fetch(params, "sort_direction")
  {:ok, sort_field} = Map.fetch(params, "sort_field")

  with {:ok, filter} <- Filtrex.parse_params(filter_config(:payments), params["payment"] || %{}),
       %Scrivener.Page{} = page <- do_paginate_payments(filter, params,doctor_id,patient_id) do
    {:ok,
      %{
        payments: page.entries,
        page_number: page.page_number,
        page_size: page.page_size,
        total_pages: page.total_pages,
        total_entries: page.total_entries,
        distance: @pagination_distance,
        sort_field: sort_field,
        sort_direction: sort_direction
      }
    }
  else
    {:error, error} -> {:error, error}
    error -> {:error, error}
  end
end

defp do_paginate_payments(filter, params,doctor_id,patient_id) do

         query = from u in  Payment,
          where: u.doctor_id == ^doctor_id and u.patient_id==^patient_id

  query
  |> Filtrex.query(filter)
  |> order_by(^sort(params))
  |> paginate(Repo, params, @pagination)
end

@doc """
Returns the list of payments.

## Examples

    iex> list_payments()
    [%Payment{}, ...]

"""
def list_payments do
  Repo.all(Payment)
end

@doc """
Gets a single payment.

Raises `Ecto.NoResultsError` if the Payment does not exist.

## Examples

    iex> get_payment!(123)
    %Payment{}

    iex> get_payment!(456)
    ** (Ecto.NoResultsError)

"""
def get_payment!(id), do: Repo.get!(Payment, id)

@doc """
Creates a payment.

## Examples

    iex> create_payment(%{field: value})
    {:ok, %Payment{}}

    iex> create_payment(%{field: bad_value})
    {:error, %Ecto.Changeset{}}

"""
def create_payment(attrs \\ %{}) do
  %Payment{}
  |> Payment.changeset(attrs)
  |> Repo.insert()
end

@doc """
Updates a payment.

## Examples

    iex> update_payment(payment, %{field: new_value})
    {:ok, %Payment{}}

    iex> update_payment(payment, %{field: bad_value})
    {:error, %Ecto.Changeset{}}

"""
def update_payment(%Payment{} = payment, attrs) do
  payment
  |> Payment.changeset(attrs)
  |> Repo.update()
end

@doc """
Deletes a Payment.

## Examples

    iex> delete_payment(payment)
    {:ok, %Payment{}}

    iex> delete_payment(payment)
    {:error, %Ecto.Changeset{}}

"""
def delete_payment(%Payment{} = payment) do
  Repo.delete(payment)
end

@doc """
Returns an `%Ecto.Changeset{}` for tracking payment changes.

## Examples

    iex> change_payment(payment)
    %Ecto.Changeset{source: %Payment{}}

"""
def change_payment(%Payment{} = payment) do
  Payment.changeset(payment, %{})
end

defp filter_config(:payments) do
  defconfig do
    number :miktar
      
  end
end

def get_sum_of_payments(doctor_id,patient_id) do
       query = from u in  Payment,
          where: u.doctor_id == ^doctor_id and u.patient_id==^patient_id , select: sum(u.miktar)
       res=Repo.one(query)
       if res do
         res
       else
         0
       end
end

end

lib/dent/payments/payment.ex
defmodule Dent.Payments.Payment do
  use Ecto.Schema
  import Ecto.Changeset

  schema "payments" do
    field :miktar, :integer
    field :doctor_id, :id
    field :patient_id, :id

    timestamps()
  end

  @doc false
  def changeset(payment, attrs) do
    payment
    |> cast(attrs, [:miktar ,:doctor_id ,:patient_id])
    |> validate_required([:miktar])
  end
end

lib/dent_web/controllers/payment_controller.ex
defmodule DentWeb.PaymentController do
  use DentWeb, :controller

  alias Dent.Payments
  alias Dent.Payments.Payment
  alias Dent.Helpers.Utils

  plug(:put_layout, {DentWeb.LayoutView, "torch.html"})

  def index(conn, params) do
    patient_id=Map.get(params,"patient_id")
    case Payments.paginate_payments(params,Utils.get_doctor_id(conn),patient_id) do
      {:ok, assigns} ->
        render(conn, "index.html", Map.put(assigns , "patient_id", patient_id))
      error ->
        conn
        |> put_flash(:error, "There was an error rendering Payments. #{inspect(error)}")
        |> redirect(to: Routes.patient_payment_path(conn, :index, patient_id: patient_id))
    end
  end

  def new(conn, params) do
    patient_id=Map.get(params,"patient_id")
    changeset = Payments.change_payment(%Payment{patient_id: patient_id})
    render(conn, "new.html", changeset: changeset  ,patient_id: patient_id)
  end

  def create(conn, %{"payment" => payment_params ,"patient_id" => patient_id}) do
    case Payments.create_payment(Map.put(Utils.add_doctor_id(payment_params,conn),"patient_id",patient_id )) do
      {:ok, payment} ->
        conn
        |> put_flash(:info, "Payment created successfully.")
        |> redirect(to: Routes.patient_payment_path(conn, :show, patient_id ,payment))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id ,"patient_id" => patient_id}) do
    #payment = Payments.get_payment!(id)
    payment= Utils.get_model(Payment,id,conn)
    render(conn, "show.html", payment: payment , id: id , patient_id: patient_id)
  end

  def edit(conn, %{"id" => id ,"patient_id" => patient_id}) do
    #payment = Payments.get_payment!(id)
    payment= Utils.get_model(Payment,id,conn)
    changeset = Payments.change_payment(payment)
    render(conn, "edit.html", payment: payment, changeset: changeset , id: id , patient_id: patient_id)
  end

  def update(conn, %{"id" => id, "payment" => payment_params  ,"patient_id" => patient_id}) do
    #payment = Payments.get_payment!(id)
    payment= Utils.get_model(Payment,id,conn)

    case Payments.update_payment(payment, payment_params) do
      {:ok, payment} ->
        conn
        |> put_flash(:info, "Payment updated successfully.")
        |> redirect(to: Routes.patient_payment_path(conn, :show, patient_id, payment))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", payment: payment, changeset: changeset)
    end
  end

  def delete(conn, %{"patient_id" => patient_id,"id" => id}) do
    #payment = Payments.get_payment!(id)
    payment= Utils.get_model(Payment,id,conn)
    {:ok, _payment} = Payments.delete_payment(payment)

    conn
    |> put_flash(:info, "Payment deleted successfully.")
    |> redirect(to: Routes.patient_payment_path(conn, :index ,patient_id ))
  end
end

lib/dent_web/views/payment_view.ex
defmodule DentWeb.PaymentView do
  use DentWeb, :view

  import Torch.TableView
  import Torch.FilterView
end

lib/dent_web/templates/payment/edit.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "Cancel", to: Routes.patient_payment_path(@conn, :index , @patient_id), class: "torch-button" %>
  </div>
</section>

<section id="torch-header-and-content">
  <div class="torch-container">
    <div class="header">
      <h3>Edit Payment</h3>
    </div>
    <%= render "form.html", Map.put(assigns, :action, Routes.patient_payment_path(@conn, :update, @patient_id, @payment)) %>
  </div>
</section>

lib/dent_web/templates/payment/form.html.eex
<%= form_for @changeset, @action, [multipart: true, id: "torch-form"], fn f -> %>
  <fieldset class="torch-panel">
    <legend>
      <span>Details</span>
    </legend>
    <%= if @changeset.action do %>
      <p class="torch-form-error">Oops, something went wrong! Please check the errors below.</p>
    <% end %>
  
    <div class="torch-form-group">
      <%= label f, :miktar %>
      <%= number_input f, :miktar %>
      <%= error_tag f, :miktar %>
    </div>
  
    <div class="torch-submit-form">
      <%= submit "Submit", class: "torch-submit-button" %>
    </div>
  </fieldset>
<% end %>

lib/dent_web/templates/payment/index.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "New Payment", to: Routes.patient_payment_path(@conn, :new , @conn.assigns["patient_id"]) %>
    <%= link "Hastanın Sayfasına Dön", to: Routes.patient_path(@conn, :show, @conn.assigns["patient_id"]) %>
  </div>
</section>
<section id="torch-index-content">
  <div class="torch-container">
    <section id="torch-filters">
      <h3>Find Payments</h3>
      <%= form_tag @conn.request_path, method: :get, id: "torch-filters-form" do %>
        
        
        
        
          <div class="field">
            <label>Miktar</label>
            <%= number_filter_select(:payment, :miktar, @conn.params) %>
            <%= filter_number_input(:payment, :miktar, @conn.params) %>
          </div>
        
        <button type="submit" class="torch-button">Search</button>
        <%= link "Clear Filters", to: Routes.patient_payment_path(@conn, :index ,  @conn.assigns["patient_id"]) %>
      <% end %>

    </section>

    <section id="torch-table">
    <%= if length(@payments) > 0 do %>
      <table>
        <thead>
          <tr>
            
              <th><%= table_link(@conn, "Miktar", :miktar) %></th>
            
            <th><span>Actions</span></th>
          </tr>
        </thead>
        <tbody>
          <%= for payment <- @payments do %>
            <tr>
              
                <td><%= payment.miktar %></td>
              
              <td class="torch-actions">
                <span><%= link "Show", to: Routes.patient_payment_path(@conn, :show, @conn.assigns["patient_id"],payment) %></span>
                <span><%= link "Edit", to: Routes.patient_payment_path(@conn, :edit, @conn.assigns["patient_id"],payment) %></span>
                <span><%= link "Delete", to: Routes.patient_payment_path(@conn, :delete, @conn.assigns["patient_id"] ,payment), method: :delete, data: [confirm: "Are you sure?"] %></span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= render Torch.PaginationView, "_pagination.html", assigns %>
    <% else %>
      <p class="torch-no-data">No Payments match your search.</p>
    <% end %>
    </section>
  </div>
</section>

lib/dent_web/templates/payment/new.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "Cancel", to: Routes.patient_payment_path(@conn, :index  , @patient_id), class: "torch-button" %>
  </div>
</section>

<section id="torch-header-and-content">
  <div class="torch-container">
    <div class="header">
      <h3>New Payment</h3>
    </div>
    <%= render "form.html", Map.put(assigns, :action, Routes.patient_payment_path(@conn, :create  , @patient_id)) %>
  </div>
</section>

lib/dent_web/templates/payment/show.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "Edit", to: Routes.patient_payment_path(@conn, :edit, @patient_id ,@payment), class: "torch-button" %>
    <%= link "Back", to: Routes.patient_payment_path(@conn, :index ,@patient_id), class: "torch-button" %>
  </div>
</section>

<section id="torch-header-and-content">
  <div class="torch-container">
    <div class="header">
      <h3>Payment Details</h3>
    </div>
    <ul>
      
        <li>
          <div class="torch-show-label">Miktar:</div>
          <div class="torch-show-data"><%= @payment.miktar %></div>
        </li>


        <li>
          <div class="torch-show-label">Oluşturulma Tarihi:</div>
          <div class="torch-show-data"><%= @payment.inserted_at %></div>
        </li>

         <li>
          <div class="torch-show-label">Son Düzenlenme Tarihi:</div>
          <div class="torch-show-data"><%= @payment.updated_at %></div>
        </li>

      
    </ul>
  </div>
</section>